/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginForm: typeof import('./components/auth/LoginForm.vue')['default']
    ProjectForm: typeof import('./components/projects/ProjectForm.vue')['default']
    ProjectList: typeof import('./components/projects/ProjectList.vue')['default']
    RegisterForm: typeof import('./components/auth/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskForm: typeof import('./components/tasks/TaskForm.vue')['default']
    TaskList: typeof import('./components/tasks/TaskList.vue')['default']
  }
}
